countrybox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
#from django.conf.urls.i18n import i18n_patterns


""" urlpatterns = [
    path("admin/", admin.site.urls),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('shopping-cart/', include('shoppingcart.urls', namespace='cart')),
    path("product/", include('products.urls')),
) """

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('shopping-cart/', include('shoppingcart.urls', namespace='cart')),
    path("product/", include('products.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppingcart/urls.py
from django.urls import path
from django.urls import path
from . import views
from .views import order_pdf_view

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('order/', views.order, name='order'),
    path('confirmation/', views.order_confirmation, name='order_confirmation'),
    path('order/pdf/', order_pdf_view, name='order_pdf'),
    
]

users/urls.py
from django.urls import path
from . import views
from .views import recipes_view, category_detail_view, meal_detail_view


urlpatterns = [
    path('', views.home_view, name='home'),
    path('user/singup/', views.signup_view, name='singup'),
    path('user/login/', views.login_view, name='login'),
    path('logout/', views.logout_view , name='logout'),
    path('list/', views.UserList, name="list_users"),
    path('recipes/', views.recipes_view, name='recipes'),
    path('recipes/<str:category_name>/', category_detail_view, name='category_detail'),
    path('meal/<int:meal_id>/', meal_detail_view, name='meal_detail'),


]

users/templates/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans " Home " %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-navbar-custom sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'Logo.png' %}" alt="Logo" style="height: 40px;">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarContent">
                {% if not is_login_page %}
                    <div class="navbar-nav">
                        <a href="{% url 'list' %}" class="nav-link">{% trans " See products " %}</a>
                    </div>
               <!-- Aquí comienza el formulario de búsqueda actualizado -->
                    <form class="d-flex flex-grow-1 mx-4" action="{% url 'search' %}" method="get">
                        <input class="form-control me-2 search-input" type="search" placeholder="{% trans " Search products, brands and more... " %}" aria-label="Search" name="q">
                        <button class="btn btn-search" type="submit">
                        <!-- Icono de búsqueda -->
                        </button>
                    </form>
                    <div class="navbar-nav">
                        {% if user.is_authenticated  %}
                            {% if not user.is_staff %}
                                <a href="{% url 'cart:cart' %}" class="nav-link">{% trans " Shopping Cart " %}</a>
                                <a href="{% url 'recipes' %}" class="nav-link">{% trans "Recipes" %}</a>
                            {% endif %}
                            <a href="{% url 'logout' %}" class="nav-link">{% trans " Log out " %}</a>
                        {% else %}
                            <a href="{% url 'login' %}" class="nav-link">{% trans " Sign in " %}</a>
                            <a href="{% url 'singup' %}" class="nav-link">{% trans " Sing up " %} </a>
                        {% endif %}
                        {% if user.is_staff %}
                            <a href="{% url 'create' %}" class="nav-link">{% trans " Create product " %}</a>
                            <a href="{% url 'list_users' %}" class="nav-link">{% trans " List of users " %}</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        {% block content %}
        <!-- El contenido dinámico irá aquí -->
        {% endblock %}
    </div>  

  <!-- Footer -->
  <footer class="footer mt-auto py-3">
    <div class="container text-center">
      <span class="text-muted">{% trans " © 2024 CountryBox. All rights reserved. " %} </span>
    </div>
<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go">
</form>
  </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

users/templates/templates/category_detail.html
<!-- users/templates/category_detail.html -->
{% extends "templates/base.html" %}

{% block content %}
<div class="category-container">
    <h1 class="category-title">{{ category_name }}</h1>
    <div class="meals-list">
        {% for meal in meals.meals %}
            <div class="meal-item">
                <a href="{% url 'meal_detail' meal.idMeal %}" class="meal-link">
                    <img src="{{ meal.strMealThumb }}" alt="{{ meal.strMeal }}" class="meal-thumb">
                    <p class="meal-name">{{ meal.strMeal }}</p>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

users/templates/templates/home.html
{% extends "templates/base.html" %}
{% block content %}
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
    <title> {% trans " Home " %} </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <!-- Bootstrap Carousel (Slider) -->
    <div id="homeCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ul class="carousel-indicators">
        <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#homeCarousel" data-slide-to="1"></li>
        <li data-target="#homeCarousel" data-slide-to="2"></li>
        <li data-target="#homeCarousel" data-slide-to="3"></li>
      </ul>

      <!-- The slideshow -->
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static '1.jpg' %}" alt="Slide 1" class="d-block w-100">
        </div>
        <div class="carousel-item">
          <img src="{% static '2.jpg' %}" alt="Slide 2" class="d-block w-100">
        </div>
        <div class="carousel-item">
          <img src="{% static '3.jpg' %}" alt="Slide 3" class="d-block w-100">
        </div>
        <div class="carousel-item">
          <img src="{% static '4.jpg' %}" alt="Slide 4" class="d-block w-100">
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#homeCarousel" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </a>
      <a class="carousel-control-next" href="#homeCarousel" data-slide="next">
        <span class="carousel-control-next-icon"></span>
      </a>
    </div>  

    <div class="container px-4 py-5" id="hanging-icons">
      <h2 class="pb-2 border-bottom"> {% trans " Our recommended " %}</h2>
      <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <!-- Aquí comienza la tarjeta de recomendados -->
        <div class="col d-flex align-items-start">
          <div>
            <h3 class="fs-2">{{ obj_1.name }}</h3>
            <a href="{% url 'details' id=obj_1.id %}">
            <img src="{{ obj_1.image_product.url }}" class="img-thumbnail" alt="Producto 1">
            </a>
            <a href="{% url 'details' id=obj_1.id %}" class="btn btn-primary mt-3">
              {% trans " Details " %}
            </a>
          </div>
        </div>
        <div class="col d-flex align-items-start">
          <div>
            <h3 class="fs-2">{{ obj_2.name }}</h3>
            <a href="{% url 'details' id=obj_1.id %}">
            <img src="{{ obj_2.image_product.url }}" class="img-thumbnail" alt="Producto 2">
            </a>
            <a href="{% url 'details' id=obj_2.id %}" class="btn btn-primary">
              {% trans " Details " %}
            </a>
          </div>
        </div>
        <div class="col d-flex align-items-start">
          <div>
            <h3 class="fs-2">{{ obj_3.name }}</h3>
            <a href="{% url 'details' id=obj_1.id %}">
            <img src="{{ obj_3.image_product.url }}" class="img-thumbnail" alt="Producto 3">
            </a>
            <a href="{% url 'details' id=obj_3.id %}" class="btn btn-primary">
              {% trans " Details " %}
            </a>
          </div>
        </div>
      </div>
    </div>
    <!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


</body>
</html>
{% endblock %}

users/templates/templates/meal_detail.html
<!-- users/templates/meal_detail.html -->
{% extends "templates/base.html" %}

{% block content %}
<h1>{{ meal.strMeal }}</h1>
<img src="{{ meal.strMealThumb }}" alt="{{ meal.strMeal }}" style="width:300px;height:300px;">
<p>{{ meal.strInstructions }}</p>
<ul>
    {% for item in ingredients %}
        <li>{{ item.ingredient }} - {{ item.measure }}</li>
    {% endfor %}
</ul>
{% endblock %}

users/templates/templates/recipes.html
<!-- users/templates/recipes.html -->
{% extends "templates/base.html" %}
{% block content %}
{% load i18n %}
<div class="recipes-container">
    <h1 class="recipes-title">{% trans " Recipes " %}</h1>
    <ul class="recipes-list">
        {% for category in categories.categories %}
            <li class="recipes-item">
                <a href="{% url 'category_detail' category.strCategory %}" class="recipes-link">{{ category.strCategory }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}