countrybox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
#from django.conf.urls.i18n import i18n_patterns


""" urlpatterns = [
    path("admin/", admin.site.urls),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('shopping-cart/', include('shoppingcart.urls', namespace='cart')),
    path("product/", include('products.urls')),
) """

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('shopping-cart/', include('shoppingcart.urls', namespace='cart')),
    path("product/", include('products.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppingcart/urls.py
from django.urls import path
from django.urls import path
from . import views
from .views import order_pdf_view

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('order/', views.order, name='order'),
    path('confirmation/', views.order_confirmation, name='order_confirmation'),
    path('order/pdf/', order_pdf_view, name='order_pdf'),
    
]

users/urls.py
from django.urls import path
from . import views
from .views import recipes_view, category_detail_view, meal_detail_view


urlpatterns = [
    path('', views.home_view, name='home'),
    path('user/singup/', views.signup_view, name='singup'),
    path('user/login/', views.login_view, name='login'),
    path('logout/', views.logout_view , name='logout'),
    path('list/', views.UserList, name="list_users"),
    path('recipes/', views.recipes_view, name='recipes'),
    path('recipes/<str:category_name>/', category_detail_view, name='category_detail'),
    path('meal/<int:meal_id>/', meal_detail_view, name='meal_detail'),


]

shoppingcart/models.py
from django.db import models
from users.models import CustomUser
from products.models import Product


class Cart(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.product.name} ({self.quantity})"

    def get_total_price(self):
        return self.product.price * self.quantity

    
    @classmethod
    def all(cls):
        return cls.objects.all()


class Order(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    address = models.CharField(max_length=255, default='Dirección predeterminada')


    def __str__(self):
        return f"Order {self.pk}"
    
    def get_total_quantity(self):
        total_quantity = 0
        for item in self:
            total_quantity += item.quantity
        return total_quantity

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.product.name} ({self.quantity})"

    def get_total_price(self):
        return self.price * self.quantity
    
    def get_total_cart_price(self):
        total_price = sum(item.get_total_price() for item in self.cartitem_set.all())
        return total_price


    @classmethod
    def all(cls):
        return cls.objects.all()

shoppingcart/forms.py
from django import forms

class PaymentForm(forms.Form):
    payment_method = forms.ChoiceField(
        label="Método de pago",
        choices=(('Cash', 'Pago en efectivo'), ('Card', 'Pago con tarjeta')),
        widget=forms.RadioSelect,
        initial='Cash',
    )
    card_number = forms.CharField(label="Número de la tarjeta", max_length=16, required=False)
    card_expiration_date = forms.CharField(label="Fecha de expiración (MM/AA)", max_length=5, required=False)
    card_holder = forms.CharField(label="Titular de la tarjeta", max_length=100, required=False)
    card_bank = forms.CharField(label="Banco", max_length=100, required=False)
    card_cvv = forms.CharField(label="CVV", max_length=3, required=False)

    def clean(self):
        cleaned_data = super().clean()
        payment_method = cleaned_data.get("payment_method")
        if payment_method == 'Card':
            if not all([cleaned_data.get("card_number"), cleaned_data.get("card_expiration_date"),
                        cleaned_data.get("card_holder"), cleaned_data.get("card_bank"), cleaned_data.get("card_cvv")]):
                raise forms.ValidationError("Todos los campos de la tarjeta de crédito son obligatorios para pagos con tarjeta.")
        return cleaned_data

shoppingcart/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .utils import ShoppingCart
from .models import Cart, CartItem ,Order, OrderItem
from products.models import Product
from users.models import CustomUser
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import PaymentForm
from .utils import OrderPDFGenerator
from django.shortcuts import render


@login_required
def cart(request):
    customer_id = request.user.id
    customer = CustomUser.objects.get(pk=customer_id)
    cart, create = Cart.objects.get_or_create(customer=customer)
    cart_items = CartItem.objects.filter(cart=cart.pk)
    cart_item = ShoppingCart(request)
    total_cart = cart_item.get_total(cart.pk)
    return render(request, 'cart.html', {'cart': cart, 'cart_items': cart_items,'customer': customer, 'total': total_cart})


@login_required
def add_to_cart(request, product_id):
    cart_item = ShoppingCart(request)
    cart = cart_item.get_cart(request)
    if Product.objects.filter(id=product_id).exists():
        quantity = int(request.POST.get('quantity', 1))
        cart_item.add_product(cart.id, product_id, quantity)
        return redirect('cart:cart')
    else:
        return HttpResponse("El producto no existe en la base de datos.")


@login_required
def remove_from_cart(request, product_id):
    product = Product.objects.get(pk=product_id)
    cart_item = ShoppingCart(request)
    cart = cart_item.get_cart(request)
    cart_item.remove_product(cart.pk ,product_id)
    messages.success(request, f'Producto "{product.name}" eliminado del carrito')
    return redirect('cart:cart')


@login_required
def order(request):
    customer_id = request.user.id
    customer = CustomUser.objects.get(pk=customer_id)
    cart, create = Cart.objects.get_or_create(customer=customer)
    cart_items = CartItem.objects.filter(cart=cart.pk)
    total_cart = sum(item.get_total_price() for item in cart_items)
    total_quantity = ShoppingCart.get_total_quantity(cart.items.all())

    if request.method == "POST":
        address = request.POST.get("address")
        payment_method = request.POST.get("payment_method")
        
        if payment_method == "Card":
            card_number = request.POST.get("card_number")
            card_expiration_date = request.POST.get("card_expiration_date")
            card_holder = request.POST.get("card_holder")
            card_bank = request.POST.get("card_bank")
            card_cvv = request.POST.get("card_cvv")


        order = Order.objects.create(
            cart=cart,
            customer=customer,
            address=address,
            total_price=total_cart,
        )

        for item in cart_items:
            OrderItem.objects.create(
                order=order,
                product=item.product,
                quantity=item.quantity,
                price=item.product.price,
            )


        cart.items.all().delete()
        
        messages.success(request, "Your order has been created!")
        return redirect("cart:order_confirmation")

    return render(request, "order.html", {
        "cart": cart,
        "cart_items": cart_items,
        "customer": customer,
        "total_price": total_cart,
        "total_quantity": total_quantity
    })


@login_required
def order_confirmation(request):
    cart = Cart.objects.get(customer=request.user)
    cart.items.all().delete()

    return render(request, "order_confirmation.html")

# shoppingcart/views.py
from django.http import HttpResponse
from .utils import OrderPDFGenerator

def order_pdf_view(request):
    # Gather order details
    order_details = {
        'product': 'Maple Taffy',
        'quantity': 1,
        'price': 20000,
        'total': 20000,
        'customer_name': 'carlitos',
        'delivery_address': 'Cll 100A Crr99B #312',
        'box_size': 'Small box: maximum 10 products',
        'total_price': 20000,
    }

    # Create the response object
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="order.pdf"'

    # Create context
    context = {
        'response': response,
        'order_details': order_details,
        'filename': 'Order Details',
    }

    # Generate the PDF
    pdf_generator = OrderPDFGenerator()
    pdf_generator.generate(context)

    return response

shoppingcart/templates/cart.html
{% extends "templates/base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Shopping Cart" %}</h2>
{% if user.is_authenticated %}
    {% if not user.is_staff %}    
        {% if cart_items %}
            <div class="customer-info box">
                <h3>{% trans "User Information:" %}</h3>
                <p>{% trans "Name:" %} {{ customer.username }}</p>
                <p>{% trans "Email:" %} {{ customer.email }}</p>
                <p>{% trans "Mobile:" %} {{ customer.phone_number }}</p>
            </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>{% trans "Product" %}</th>
                            <th>{% trans "Quantity" %}</th>
                            <th>{% trans "Unit Price" %}</th>
                            <th>{% trans "Total Price" %}</th>
                            <th></th>                            
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart_items %}
                            <tr>
                                <td>{{ item.product.name }}</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.product.price }}</td>
                                <td>{{ item.get_total_price }}</td>
                                <td><a href="{% url 'cart:remove_from_cart' item.product.id %}">{% trans " Remove " %}</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <a href="{% url 'cart:order' %}"  class="btn btn-primary">{% trans " Check " %}</a>
            {% endif %}
        {% endif %}
    {% endif %}
{% endblock %}

shoppingcart/templates/order.html
{% extends 'templates/base.html' %}
{% load i18n %}
{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
  {% endif %}
  <h1>{% trans "Order Details" %}</h1>
  <table class="table">
    <thead>
      <tr>
        <th>{% trans "Product" %}</th>
        <th>{% trans "Quantity" %}</th>
        <th>{% trans "Price" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart_items %}
        <tr>
          <td>{{ item.product.name }}</td>
          <td>{{ item.quantity }}</td>
          <td>${{ item.get_total_price }}</td>
        </tr>
      {% endfor %}
      <tr>
        <td><b>{% trans "Total" %}</b></td>
        <td>{{ total_quantity }}</td>
        <td><b>${{ total_price }}</b></td>
      </tr>
    </tbody>
  </table>
  
  <h3 style="margin-top: 20px;">{% trans "Delivery Information:" %}</h3>
  <p>{% trans "Name:" %} {{ customer.username }}</p>
  <form method="post" action="{% url 'cart:order' %}">
    {% csrf_token %}
    <div style="margin-top: 20px;">
      <label for="address">{% trans "Delivery Address" %}</label>
      <input type="text" id="address" name="address" required>
    </div>

    <h5 style="margin-top: 20px;">{% trans "Box Size:" %}</h5>
    {% if total_quantity <= 10 %}
      <p>{% trans "Small box: maximum 10 products" %}</p>
    {% elif total_quantity <= 20 %}
      <p>{% trans "Medium box: maximum 20 products" %}</p>
    {% elif total_quantity <= 30 %}
      <p>{% trans "Large box: maximum 30 products" %}</p>
    {% endif %}

    <p style="margin-top: 20px;">{% trans "Total to pay:" %} ${{ total_price }}</p>

    <h5 style="margin-top: 20px;">{% trans "Payment Method" %}</h5>
    <div style="margin-top: 10px;">
      <label style="margin-right: 20px;">
        <input type="radio" name="payment_method" value="Cash" checked> {% trans "Cash" %}
      </label>
      <label>
        <input type="radio" name="payment_method" value="Card"> {% trans "Card" %}
      </label>
    </div>

    <div id="card-details" style="display: none; margin-top: 20px; border: 1px solid #ddd; padding: 15px; border-radius: 5px; max-width: 25%;">
      <div style="margin-top: 10px;">
        <label for="card_number">{% trans "Card Number" %}</label>
        <input type="text" id="card_number" name="card_number" style="width: 100%;">
      </div>
      <div style="margin-top: 10px;">
        <label for="card_expiration_date">{% trans "Expiration Date" %}</label>
        <input type="text" id="card_expiration_date" name="card_expiration_date" style="width: 100%;">
      </div>
      <div style="margin-top: 10px;">
        <label for="card_holder">{% trans "Card Holder" %}</label>
        <input type="text" id="card_holder" name="card_holder" style="width: 100%;">
      </div>
      <div style="margin-top: 10px;">
        <label for="card_bank">{% trans "Bank" %}</label>
        <input type="text" id="card_bank" name="card_bank" style="width: 100%;">
      </div>
      <div style="margin-top: 10px;">
        <label for="card_cvv">{% trans "CVV" %}</label>
        <input type="text" id="card_cvv" name="card_cvv" style="width: 100%;">
      </div>
    </div>

    <div class="form-buttons" style="margin-top: 20px;">
      <button type="submit" class="btn btn-success" style="margin-right: 10px;">{% trans "Confirm Order" %}</button>
      <a href="{% url 'cart:cart' %}" class="btn btn-danger">{% trans "Cancel Order" %}</a>
    </div>
  </form>
  <p><a href="{% url 'list' %}">{% trans "Continue Shopping" %}</a></p>

  <script>
    document.addEventListener('DOMContentLoaded', function () {
        const paymentMethodRadios = document.querySelectorAll('input[name="payment_method"]');
        const cardDetails = document.getElementById('card-details');

        paymentMethodRadios.forEach(radio => {
            radio.addEventListener('change', function () {
                if (this.value === 'Card') {
                    cardDetails.style.display = 'block';
                } else {
                    cardDetails.style.display = 'none';
                }
            });
        });

        // Initial check
        const selectedPaymentMethod = document.querySelector('input[name="payment_method"]:checked');
        if (selectedPaymentMethod && selectedPaymentMethod.value === 'Card') {
            cardDetails.style.display = 'block';
        }
    });
  </script>
  <a href="{% url 'cart:order_pdf' %}" class="btn btn-primary">{% trans "Download PDF" %}</a>

{% endblock %}

shoppingcart/templates/order_confirmation.html
{% extends "templates/base.html" %}
{% load i18n %}
{% block content %}
<div class="container mt-5">
    <div class="py-5 text-center">
        <h2 class="display-4">{% trans "Order Confirmation" %}</h2>
        <p class="lead">{% trans "Thank you for your purchase!" %}</p>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-7 col-lg-5">
            <div class="alert alert-success" role="alert">
                {% trans "Your order has been processed successfully." %}
            </div>
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{% trans "Order Details" %}</h5>
                    <p class="card-text">{% trans "Go back to the home to continue shopping." %}</p>
                    <div class="d-grid gap-2">
                        <a href="{% url 'home' %}" class="btn btn-outline-primary">{% trans "Back to Home" %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}