countrybox/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
#from django.conf.urls.i18n import i18n_patterns


""" urlpatterns = [
    path("admin/", admin.site.urls),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('shopping-cart/', include('shoppingcart.urls', namespace='cart')),
    path("product/", include('products.urls')),
) """

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('shopping-cart/', include('shoppingcart.urls', namespace='cart')),
    path("product/", include('products.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
from api.views import ProductListViewApi

urlpatterns = [
    path('create/', views.ProductCreateView, name='create'),
    path('list/', views.ProductListView, name='list'),
    path('denied/', views.access_denied, name='access_denied'),
    path('details/<int:id>/', views.ProductDetailsView, name='details'),
    path('delete/<int:id>/', views.ProductDelete, name='delete'),
    path('search/', views.search, name='search'),
    path('countrybox-api/', ProductListViewApi.as_view(), name='api'),

]

shoppingcart/urls.py
from django.urls import path
from django.urls import path
from . import views
from .views import order_pdf_view

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('order/', views.order, name='order'),
    path('confirmation/', views.order_confirmation, name='order_confirmation'),
    path('order/pdf/', order_pdf_view, name='order_pdf'),
    
]

users/urls.py
from django.urls import path
from . import views
from .views import recipes_view, category_detail_view, meal_detail_view


urlpatterns = [
    path('', views.home_view, name='home'),
    path('user/singup/', views.signup_view, name='singup'),
    path('user/login/', views.login_view, name='login'),
    path('logout/', views.logout_view , name='logout'),
    path('list/', views.UserList, name="list_users"),
    path('recipes/', views.recipes_view, name='recipes'),
    path('recipes/<str:category_name>/', category_detail_view, name='category_detail'),
    path('meal/<int:meal_id>/', meal_detail_view, name='meal_detail'),


]

products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=255)
    description=models.CharField(max_length=255)
    country=models.CharField(max_length=255)
    size=models.CharField(max_length=255)
    image_product= models.ImageField(upload_to='products/images/', default= 'products/images/box.jpg')
    price=models.IntegerField()

products/forms.py
from django import forms
from .models import Product
from django.utils.translation import gettext_lazy as _


class ProductForm(forms.ModelForm):
    
    COUNTRYS_CHOICES = [
        ('JP', _("Japan")),
        ('BR', _("Brazil")),
        ('CA', _("Canada")),
        ('RU', _("Russia")),
    ]
    
    SIZE_CHOICES = [
        ('L', _("Large")),
        ('M', _("Medium")),
        ('S', _("Small")),    
    ]
    
    name = forms.CharField(label=_("Name"),max_length=255)
    description = forms.CharField(label=_("Description"),max_length=255, widget=forms.Textarea())
    country = forms.ChoiceField(choices = COUNTRYS_CHOICES, label=_("Country"))
    size = forms.ChoiceField(choices = SIZE_CHOICES, label=_("Size"))
    image_product = forms.ImageField(required=False, label=_("Image of product"))
    price = forms.IntegerField(min_value=0, label=_("Price"))
    
    class Meta:
        model = Product
        fields = [
            'name',
            'description',
            'country',
            'size',
            'image_product',
            'price',
        ]

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseForbidden
from .models import Product
from .forms import ProductForm
from users import views
from users.utils import is_staff
from django.db.models import Q

# Create your views here.


@user_passes_test(is_staff, login_url="/product/denied/")
def ProductCreateView(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product_form = form.save()
            return redirect(views.home_view)
        
    else:
        return render(request, 'products/create.html', { 'form': ProductForm})


def ProductListView(request):
    orden = request.GET.get('orden')

    if orden == 'desc':
        products = Product.objects.all().order_by('-price')  # Orden descendente
    elif orden == 'asc':
        products = Product.objects.all().order_by('price')   # Orden ascendente o cualquier otro orden por defecto
    else:
        products = Product.objects.all()
    return render(request, "products/list.html", {"products": products})


def ProductDetailsView(request, id):
    if Product.objects.filter(id=int(id)).exists():
        try:
            product_id = int(id)
            if product_id < 1:
                raise ValueError("El id del producto debe ser mayor a 1")
            product = get_object_or_404(Product, pk=product_id)
        
        except (ValueError, IndexError):
            return redirect('home')
    else:
        return redirect('home')
        
    return render(request, 'products/details.html', { 'product': product })


def ProductDelete(request, id):
    if Product.objects.filter(id=int(id)).exists():
        try:
            product_id = int(id)
            
            if product_id < 1:
                raise ValueError("El id del producto debe ser mayor a 1")
            
            product = get_object_or_404(Product, pk=product_id)
            
            product.delete()
        
        except (ValueError, IndexError):
            return redirect('home')
    else:
        return redirect('home')
        
    return redirect('list')


#------------Other Functions--------------------


def access_denied(request):
    return HttpResponseForbidden("No tienes permiso para acceder a esta página.")

# views.py en la aplicación products
def search(request):
    query = request.GET.get('q', '')
    products = Product.objects.filter(
        Q(name__icontains=query) |
        Q(description__icontains=query) |
        Q(country__icontains=query)
    )
    return render(request, 'products/searchresults.html', {'products': products})
  

products/templates/products/create.html
{% extends "templates/base.html" %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title> {% trans " Create product " %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
  <style>
    .btn-custom {
      background-color: #97D2FB;
      border-color: #97D2FB;
    }
    .btn-custom:hover {
      background-color: #86C2EF;
      border-color: #86C2EF;
    }
  </style>
</head>
{% block content %}
<body>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title text-center mb-4"> {% trans " Create product " %}</h3>
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
                <div class="mb-3">
                  <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                  {% if field.widget.input_type == 'checkbox' %}
                    <div class="form-check">
                      {{ field }}
                      <label for="{{ field.id_for_label }}" class="form-check-label">{{ field.label }}</label>
                    </div>
                  {% else %}
                    {{ field }}
                  {% endif %}
                  {% for error in field.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                  {% endfor %}
                </div>
              {% endfor %}
              <div class="d-grid">
                <button type="submit" class="btn btn-custom">{% trans " Save " %}</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}
</html>

products/templates/products/details.html
{% extends 'templates/base.html' %} 
{% load i18n %} 
{% load static %}
{% block content %}
<div class="card mb-3">
  <div class="row g-0 mt-4">
    <div class="col-md-4">
      <img
        src="{{ product.image_product.url }}" class="img-fluid rounded-start ms-5"
      />
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-6">
      <div class="card-body">
        <h5 class="card-title">
          <p class="card-text">{{product.name}}</p>
        </h5>
        <p class="card-text">{% trans "Description:" %} {{product.description}}</p>
        <p class="card-text">{% trans "Country of origin:" %} {{product.country}}</p>
        <p class="card-text">{% trans "Product size:" %} {{product.size}}</p>
        <p class="card-text">{% trans "Price:" %} ${{product.price}}</p>        
        <div class="row">
          <div class="mt-3">
            <form method="post" action="{% url 'cart:add_to_cart' product.id %}">
              {% csrf_token %}
              {% if user.is_authenticated  %}
              {% if not user.is_staff %}
              <label for="quantity"> {% trans " Quantity: " %} </label>
              <input type="number" name="quantity" min="1" value="1">
              <button type="submit" class="btn btn-success"> {% trans " Add to cart " %} </button>
              {% endif %}
              {% endif %}
          </form>
        </div>
        {% if user.is_staff %}
          <div class="col-4 mt-4">
            <a
              href="{% url 'delete' id=product.id %}"
              class="btn btn-danger"
              role="button"
              aria-disabled="true"
              >{% trans " Remove " %}</a>
          </div>
        {% endif %}    
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

products/templates/products/list.html
{% extends "templates/base.html" %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% trans " List " %} </title>
</head>
{% block content %}
<body>
    <div class="row">
      <div class="col-4">
          <!-- Ordenar de mayor a menor -->
          <a href="?orden=desc">{% trans "Sort Descending" %}</a>
      </div>
      <div class="col-4">
          <!-- Ordenar de menor a mayor -->
          <a href="?orden=asc">{% trans "Sort Ascending" %}</a>
      </div>
  </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-4">
          {% for product in products %}
          <div class="col">
            <div class="card h-100 d-flex flex-column">
                <a href="{% url 'details' id=product.id %}">
                    <img src="{{ product.image_product.url }}" class="card-img-top" alt="{{ product.name }}">
                </a>                
                <div class="card-body">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <p class="card-text">{{ product.description }}</p>
                  <p class="card-text"><strong>{% trans "Country:" %}</strong> {{ product.country }}</p>
                  <p class="card-text"><strong>{% trans "Size:" %}</strong> {{ product.size }}</p>
                  <p class="card-text"><strong>{% trans "Price:" %}</strong> {{ product.price }}</p>
                </div>
                <div class="card-footer mt-auto">
                  <a href="{% url 'details' id=product.id %}" class="btn bg-warning text-white">{% trans "Details" %}</a>
                </div>                
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
</body>
{% endblock %}
</html>

products/templates/products/searchresults.html
{% extends "templates/base.html" %}
{% load i18n %}
{% block content %}
<div class="container mt-4">
    <h2>{% trans "Search Results" %}</h2>
    <div class="row">
        {% for product in products %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <img src="{{ product.image_product.url }}" class="card-img-top" alt="{{ product.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text">{{ product.country }}</p>
                    <p class="card-text">{{ product.price }}</p>
                    <a href="{% url 'details' product.id %}" class="btn btn-primary">{% trans "Details" %}</a>
                </div>
            </div>
        </div>
        {% empty %}
        <p>{% trans "No products were found that matched your search criteria." %}</p>
        {% endfor %}
    </div>
</div>
{% endblock %}